### ISSUE TITLE
changing query endTime causes vague error

### ISSUE THREAD

**Issue by dbrakenhoff** [HKV-products-services/hkvfewspy#14]
When I query my local copy of a FEWS database with an endtime that is presumably after the last entry of the timeseries I am trying to get from the databse I get an error: `Fault: java.io.IOException`. This error doesn't tell me much, and there is a bunch more output I can't quite understand in the console in which the database was started (see below). 

I was wondering if someone can confirm whether the error is caused by me trying to get data beyond the end of a timeseries? How could I check this? Is the expected behavior for the query? Wouldn't it be nicer if instead of an error, the query returns the data up to the last valid index?

```{batch}
Feb 21, 2019 2:54:30 PM com.sun.xml.ws.server.sei.TieHandler createResponse
SEVERE: java.io.IOException
javax.xml.ws.WebServiceException: java.io.IOException
        at nl.wldelft.fewspiservice.server.FewsPiServiceImpl.getTimeSeries(FewsPiServiceImpl.java:477)
        at nl.wldelft.fewspiservice.server.FewsPiServiceImpl.getTimeSeries(FewsPiServiceImpl.java:424)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
        at java.lang.reflect.Method.invoke(Unknown Source)
        at com.sun.xml.ws.api.server.InstanceResolver$1.invoke(InstanceResolver.java:250)
        at com.sun.xml.ws.server.InvokerTube$2.invoke(InvokerTube.java:149)
        at com.sun.xml.ws.server.sei.SEIInvokerTube.processRequest(SEIInvokerTube.java:88)
        at com.sun.xml.ws.api.pipe.Fiber.__doRun(Fiber.java:1136)
        at com.sun.xml.ws.api.pipe.Fiber._doRun(Fiber.java:1050)
        at com.sun.xml.ws.api.pipe.Fiber.doRun(Fiber.java:1019)
        at com.sun.xml.ws.api.pipe.Fiber.runSync(Fiber.java:877)
        at com.sun.xml.ws.server.WSEndpointImpl$2.process(WSEndpointImpl.java:420)
        at com.sun.xml.ws.transport.http.HttpAdapter$HttpToolkit.handle(HttpAdapter.java:687)
        at com.sun.xml.ws.transport.http.HttpAdapter.handle(HttpAdapter.java:266)
        at com.sun.xml.ws.transport.http.servlet.ServletAdapter.invokeAsync(ServletAdapter.java:225)
        at com.sun.xml.ws.transport.http.servlet.WSServletDelegate.doGet(WSServletDelegate.java:161)
        at com.sun.xml.ws.transport.http.servlet.WSServletDelegate.doPost(WSServletDelegate.java:197)
        at com.sun.xml.ws.transport.http.servlet.WSServlet.doPost(WSServlet.java:81)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:650)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:731)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:303)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
        at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
        at nl.wldelft.fewspiservice.server.CorsFilter.doFilter(CorsFilter.java:62)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
        at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:218)
        at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:110)
        at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:506)
        at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:169)
        at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:103)
        at org.apache.catalina.valves.AccessLogValve.invoke(AccessLogValve.java:962)
        at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:116)
        at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:445)
        at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1115)
        at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:637)
        at org.apache.tomcat.util.net.AprEndpoint$SocketProcessor.doRun(AprEndpoint.java:2549)
        at org.apache.tomcat.util.net.AprEndpoint$SocketProcessor.run(AprEndpoint.java:2538)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
        at java.lang.Thread.run(Unknown Source)
Caused by: java.io.IOException
        at nl.wldelft.fewspiservice.util.SerializerUtilsImpl.toString(SerializerUtilsImpl.java:143)
        at nl.wldelft.fewspiservice.util.SerializerUtilsImpl.toString(SerializerUtilsImpl.java:119)
        at nl.wldelft.fewspiservice.server.FewsPiServiceImpl.getTimeSeries(FewsPiServiceImpl.java:473)
        ... 45 more
Caused by: java.lang.NullPointerException
        at nl.wldelft.fews.system.data.timeseries.TimeSeriesExportContent.toFlagSourceString(TimeSeriesExportContent.java:1207)
        at nl.wldelft.fews.system.data.timeseries.TimeSeriesExportContent.getColumnFlagSource(TimeSeriesExportContent.java:1199)
        at nl.wldelft.fews.pi.PiSerializerUtils.writeFlagsUserComment(PiSerializerUtils.java:129)
        at nl.wldelft.fews.pi.PiTimeSeriesSerializer.writeXmlEvents(PiTimeSeriesSerializer.java:449)
        at nl.wldelft.fews.pi.PiTimeSeriesSerializer.writeEvents(PiTimeSeriesSerializer.java:399)
        at nl.wldelft.fews.pi.PiTimeSeriesSerializer.serializeContent(PiTimeSeriesSerializer.java:165)
        at nl.wldelft.fews.pi.PiTimeSeriesSerializer.serializeContent(PiTimeSeriesSerializer.java:34)
        at nl.wldelft.util.io.XmlChunkedSerializer.serialize(XmlChunkedSerializer.java:51)
        at nl.wldelft.fewspiservice.util.SerializerUtilsImpl.toString(SerializerUtilsImpl.java:133)
        ... 47 more
```

**Comment by mattijn** [comment]
If I query data beyond the end of a time-series then these will return as missing values (flag 8). 
Your error report doesn't tell me much regarding endTime issues. I suspect something else is wrong.

**Comment by dbrakenhoff** [comment]
The only thing I changed in my code is the endTime. This is the snippet of code that works up to 2016-11-30 but results in the error I mentioned earlier when I set the data to 2016-12-01. I'm running a local standalone copy of the FEWS database. 

```{python}
from hkvfewspy import Pi
from pandas import Timestamp

tmin = Timestamp("1996")
tmax = Timestamp("2016-11-30")  # works
# tmax = Timestamp("2016-12-01")  # fails

locationId = "66004cal"
parameterId = "P.meting.dagcal"

query = pi.setQueryParameters(prefill_defaults=True)
query.query["onlyManualEdits"] = False
query.parameterIds([parameterId])
query.locationIds([locationId])
query.startTime(tmin)
query.endTime(tmax)
df = pi.getTimeSeries(query, setFormat='df')
```
Perhaps something else is causing the issue, but it would be nice to know what that is so I can take it into account as i'm writing my scripts. Any help is greatly appreciated!

**Comment by mattijn** [comment]
Which FEWS version are you talking against?

**Comment by mattijn** [comment]
There is different behavior between embedded FEWS SOAP services (stripped-down) and the one that runs in tomcat (extended). This is especially the case from 2017.02 onwards.

For previous FEWS versions that run locally you might try using the function `getTimeSeriesForFilter2()`. Its a deprecated function, but it uses a different entry point in the FewsPi service that might work sometimes better on a local standalone version.

**Comment by dbrakenhoff** [comment]
I assume this means I'm on version 2017.01

![image](https://user-images.githubusercontent.com/6552225/53721945-ab1d8100-3e64-11e9-871a-983b7c9c6503.png)

Using the `getTimeSeriesForFilter2()` function isn't working for me at the moment. The function crashes on trying to get the timeseries for the embedded FewsPi services. It throws a `TypeError`, which according to the code should be caught after which it attempts to use the second call for the tomcat webservice. But while handling that exception it also throws a `Fault: No time series content found for current selection!` which crashes the whole thing. 

I'm gonna let this rest for now, as I heard they're going to update the local FEWS database I'm working with. So we'll see how that changes things. 

(PS. I had to add `import zeep` to soap_fewspi.py to avoid a `NameError` caused by line 620.)

**Comment by mattijn** [comment]
Your last sentence is fixed in version `0.6.3`

I also got this Fault of no time series content found. Its an FEWS java error. Maybe we can catch it and return a warning in combination with an empty dataframe

**Comment by dbrakenhoff** [comment]
An update on this issue. I'm now on 2017.02 and I still get this error (`Fault: java.io.IOException`) when attempting to get precipitation timeseries through hkvfewspy `pi.getTimeSeries()`. Doing the same query through the test page of the SOAP service _does_ work. With the FEWS application I'm also able to see that there is data for the specified period.

The fact that the query is working through SOAP webservice but not from Python seems to suggest something going on with hkvfewspy, hence my update. On the other hand, the error is definitely a FEWS error. So basically I'm at a loss... So if you have any new insights or ideas how I can test what's going wrong, I appreciate it!

Below is the code snippet that will reproduce the error for me:

```python
from hkvfewspy import Pi
from pandas import Timestamp

pi = Pi()
pi.setClient(wsdl='http://localhost:8080/FewsWebServices/fewspiservice?wsdl')

tmin = Timestamp("1996")
# tmax = Timestamp("2016-11-30")  # works
tmax = Timestamp("2016-12-01")  # fails

moduleInstanceId = "ImportCAW"
locationId = "66004cal"
parameterId = "P.meting.dagcal"

query = pi.setQueryParameters(prefill_defaults=True)
query.query["onlyManualEdits"] = False
query.moduleInstanceIds([moduleInstanceId])
query.parameterIds([parameterId])
query.locationIds([locationId])
query.startTime(tmin)
query.endTime(tmax)
df = pi.getTimeSeries(query, setFormat='df')
```

**Comment by dbrakenhoff** [comment]
Problem solved, though the mystery (to me at least) remains...

Apparently the useDisplayUnits parameter had to be set to False. Only for precipitation timeseries, and only when getting data after 30 november 2016. The other methods that queried the FEWS database had a different default setting for this parameter...

So in the end, not an issue in hkvfewspy, so I'm closing it.

**Comment by mattijn** [comment]
If you have FEWS 2017.02 and hkvfewspy version 0.7 (just released) it is now also possible to use the REST protocol. It seems more strict on the query parameters and maybe resolves the mystery on the FEWS side..

**Comment by mattijn** [comment]
Example notebook for usage: https://nbviewer.jupyter.org/github/HKV-products-services/hkvfewspy/blob/master/notebooks/test%20REST%20endpoint.ipynb
